"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { Sparkles, Target } from "lucide-react";
import { createAIRepository, type DailySummary } from "@/entities/ai";
import { useCan } from "@/entities/viewer";
import { useApiQuery } from "@/shared/lib/use-api-query";
import { QueryState, useMutationFeedback } from "@/shared/ui";
import { AIConnectState, AIHeaderButton, AIInsightCard, AISkeleton } from "./ai-insight-card";

const repo = createAIRepository();

/** Today's AI briefing for managers; generated by the morning job or on demand. */
export function AIExecutiveSummaryCard() {
  const t = useTranslations("ai");
  const feedback = useMutationFeedback();
  const canRun = useCan("ai.write");
  const query = useApiQuery(() => repo.dailySummary(), [], { cacheKey: ["ai-daily-summary"] });
  const [fresh, setFresh] = useState<DailySummary | null>(null);
  const [busy, setBusy] = useState(false);
  const data = fresh ?? query.data;

  async function generate() {
    setBusy(true);
    try {
      setFresh({ ...(await repo.generateDailySummary()), aiEnabled: true });
    } catch (err) {
      feedback.error(err, t("execError"));
    } finally {
      setBusy(false);
    }
  }

  const enabled = Boolean(data?.aiEnabled);
  return (
    <AIInsightCard
      title={t("execTitle")}
      subtitle={t("execSubtitle")}
      icon={Sparkles}
      accent="violet"
      updatedAt={data?.available ? data.createdAt : undefined}
      data-testid="ai-executive-summary"
      action={
        enabled && canRun ? (
          <AIHeaderButton onClick={() => void generate()} disabled={busy}>
            {busy ? t("loading") : data?.available ? t("refresh") : t("generate")}
          </AIHeaderButton>
        ) : null
      }
    >
      <QueryState loadingVariant="lines" loading={query.loading && !data} error={fresh ? null : query.error} onRetry={() => void query.reload()}>
        {!data ? null : !enabled ? (
          <AIConnectState text={t("execNoAi")} />
        ) : busy ? (
          <AISkeleton />
        ) : !data.available ? (
          <p className="text-sm font-medium text-zinc-500">{t("execEmpty")}</p>
        ) : (
          <div className="space-y-4">
            {data.headline ? (
              <p className="text-[15px] font-semibold leading-snug text-zinc-950">{data.headline}</p>
            ) : null}
            {data.bullets.length > 0 ? (
              <ul className="space-y-2">
                {data.bullets.map((b) => (
                  <li key={b} className="flex items-start gap-2.5 text-sm leading-relaxed text-zinc-700">
                    <span aria-hidden className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500" />
                    <span>{b.replace(/^\s*[-•*]\s*/, "")}</span>
                  </li>
                ))}
              </ul>
            ) : null}
            {data.focus ? (
              <div className="flex items-start gap-2.5 rounded-2xl bg-violet-50 px-3.5 py-3 text-sm text-violet-900 ring-1 ring-violet-100">
                <Target className="mt-0.5 h-4 w-4 shrink-0 text-violet-600" aria-hidden />
                <p>
                  <span className="font-semibold">{t("focus")}: </span>
                  {data.focus}
                </p>
              </div>
            ) : null}
          </div>
        )}
      </QueryState>
    </AIInsightCard>
  );
}
