import {
  ArrowLeftRight,
  Bell,
  Briefcase,
  Building2,
  CalendarCheck2,
  FileBarChart2,
  FileSpreadsheet,
  FileWarning,
  Hotel,
  Kanban,
  LayoutDashboard,
  ListTodo,
  Lock,
  MessageSquare,
  Package,
  PlaneTakeoff,
  Rocket,
  Settings,
  Sparkles,
  Target,
  Truck,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  Compass,
  type LucideIcon,
} from "lucide-react";
import type { FaqTopicId } from "@/entities/faq";
import type { Tone } from "@/shared/ui";

/** Same glyphs as the sidebar, so a topic is recognisable as its screen. */
export const FAQ_TOPIC_LOOK: Record<FaqTopicId, { icon: LucideIcon; tone: Tone }> = {
  gettingStarted: { icon: Compass, tone: "sky" },
  account: { icon: UserRound, tone: "violet" },
  manager: { icon: LayoutDashboard, tone: "sky" },
  workspace: { icon: Briefcase, tone: "sky" },
  tasks: { icon: ListTodo, tone: "sky" },
  notifications: { icon: Bell, tone: "rose" },
  pipeline: { icon: Kanban, tone: "violet" },
  inbox: { icon: MessageSquare, tone: "violet" },
  customers: { icon: Users, tone: "violet" },
  targets: { icon: Target, tone: "violet" },
  packages: { icon: Package, tone: "emerald" },
  bookings: { icon: CalendarCheck2, tone: "emerald" },
  flights: { icon: PlaneTakeoff, tone: "emerald" },
  hotels: { icon: Hotel, tone: "emerald" },
  suppliers: { icon: Truck, tone: "emerald" },
  missingDocs: { icon: FileWarning, tone: "emerald" },
  finance: { icon: Wallet, tone: "amber" },
  fxRates: { icon: ArrowLeftRight, tone: "amber" },
  reports: { icon: FileBarChart2, tone: "amber" },
  importExport: { icon: FileSpreadsheet, tone: "indigo" },
  aiSetup: { icon: Sparkles, tone: "indigo" },
  setup: { icon: Rocket, tone: "indigo" },
  team: { icon: UsersRound, tone: "zinc" },
  settings: { icon: Settings, tone: "zinc" },
  companies: { icon: Building2, tone: "zinc" },
  privacy: { icon: Lock, tone: "teal" },
};
